#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2



start() {
	ebegin "Starting HARDLOCK daemon"
	eval start-stop-daemon --start --quiet --pidfile /var/run/aksusbd.pid --exec /usr/sbin/aksusbd --
	eend $?
}

stop() {
	ebegin "Stopping HARDLOCK daemon"
	start-stop-daemon --stop --quiet --pidfile /var/run/aksusbd.pid --exec /usr/sbin/aksusbd
	eend $?
}
