#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend () {
    need net
    after hasplmd
}

start() {
	ebegin "Starting HASP SRM"
	eval start-stop-daemon --start --quiet --pidfile /var/run/hasplmd.pid --exec /usr/sbin/hasplmd -- ${HASPLMD_ARGS}
	eend $?
}

stop() {
	ebegin "Stopping HASP SRM"
	start-stop-daemon --stop --quiet --pidfile /var/run/hasplmd.pid --exec /usr/sbin/hasplmd
	eend $?
}
